# ICT PLATFORM
# Build your Java project and run tests with Apache Maven.
# Author: Hoangl

trigger:
  branches:
    include:
    - dev
    - staging
    - releases/*
    exclude:
    - releases/old*

pool:
  name: AgentPool

variables:
- group: k8s-ci-variable

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: "17"
    jdkArchitectureOption: x64
    jdkSourceOption: LocalDirectory
    jdkFile: "$(agent.toolsDirectory)/jdk/microsoft-jdk-17.0.8-linux-x64.tar.gz"
    jdkDestinationDirectory: "$(agent.toolsDirectory)/jdk17"
    cleanDestinationDirectory: true
- script: |
   ./mvnw compile jib:build -Djib.to.image=$(REGISTRY)/$(ENV)/$(IMAGE):$(TAG) -Djib.container.entrypoint=/bin/sh,/entrypoint.sh -X -DsendCredentialsOverHttp=false -Djib.allowInsecureRegistries=true
  displayName: 'Build Image'